CREATE TABLE PESSOA (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CPF_CNPJ BIGINT NOT NULL,
	NOME_COMPLETO VARCHAR(256),
	DATA_NASCIMENTO DATE,
	RAZAO_SOCIAL VARCHAR(256),
	NOME_FANTASIA VARCHAR(256),
	TIPO_PESSOA CHAR(1) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (CPF_CNPJ)
);

CREATE INDEX IDX_TIPO_PESSOA ON PESSOA(TIPO_PESSOA);

CREATE TABLE CONTA (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ID_PESSOA INTEGER NOT NULL,
	CONTA_PAI INTEGER,
	DATA_CRIACAO DATE NOT NULL,
	NOME_CONTA VARCHAR(256),
	STATUS_CONTA VARCHAR(20),
	VALOR_SALDO NUMERIC(20,5) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX IDX_PESSOA_CONTA ON CONTA(ID_PESSOA);

CREATE TABLE TRANSACAO (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CONTA_CREDORA INTEGER NOT NULL,
	DATA_TRANSACAO DATE NOT NULL,
	CONTA_DEBITO INTEGER,
	CODIGO_EXTERNO VARCHAR(128),
	TIPO_TRANSACAO CHAR(1) NOT NULL,
	VALOR_TRANSACAO NUMERIC(20,5) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX IDX_CONTA_TRANSACAO ON TRANSACAO(CONTA_CREDORA);

CREATE INDEX IDX_TIPO_TRANSACAO ON TRANSACAO(TIPO_TRANSACAO);